name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Login to DockerHub"
        run: docker login --username ${{ secrets.DOCKERAUN }}  --password ${{ secrets.DOCKERAT }}

      - name: "Image building"
        run: docker build -t ${{ secrets.DOCKERAUN }}/javaimagetest .

      - name: "Image Pushing"
        run: docker push ${{ secrets.DOCKERAUN }}/javaimagetest
